Traceback (most recent call last):
  File "script.py", line 4, in <module>
    from runsimulation import *
  File "/home/cedric/Desktop/arduPilot/monkey-copter/runsimulation.py", line 1, in <module>
    from dronekit_sitl import SITL
ModuleNotFoundError: No module named 'dronekit_sitl'
Traceback (most recent call last):
  File "script.py", line 49, in <module>
    run(range(0,7),real_life=True,mutiple_bugs=True,mutiple_bugs_start=0)
  File "script.py", line 29, in run
    with open('/home/cedric/record/record_%d.txt'%i,'w') as f:
UnboundLocalError: local variable 'i' referenced before assignment
{'indices': [7], 'start': 10000000, 'lineno': [956], 'file': 'libraries/AC_AttitudeControl/AC_AttitudeControl.cpp'}
Traceback (most recent call last):
  File "script.py", line 49, in <module>
    run(range(0,7),real_life=True,mutiple_bugs=True,mutiple_bugs_start=0)
  File "script.py", line 35, in run
    inject_bugs(bug_id_list,real_life)
  File "/home/cedric/Desktop/arduPilot/monkey-copter/injector.py", line 414, in inject_bugs
    selected_bugs.append(group[id])
TypeError: list indices must be integers, not dict
